// 상태코드 상수화
const OK = 200;
const CREATED = 201;
const NO_CONTENT = 204;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const CONFLICT = 409;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  OK: OK,
  CREATED: CREATED,
  NO_CONTENT: NO_CONTENT,
  BAD_REQUEST: BAD_REQUEST,
  UNAUTHORIZED: UNAUTHORIZED,
  FORBIDDEN: FORBIDDEN,
  NOT_FOUND: NOT_FOUND,
  CONFLICT: CONFLICT,
  INTERNAL_SERVER_ERROR: INTERNAL_SERVER_ERROR,
};
